/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  swiftSidebar: [
    {
      type: "category",
      label: "Swift",
      collapsible: false,
      items: [
        {
          type: "category",
          label: "欢迎",
          items: [
            "swift/welcome/about/index",
            "swift/welcome/a-swift-tour/index",
          ],
        },
      ],
    },
  ],
  swiftuiSidebar: [
    {
      type: "category",
      label: "SwiftUI",
      collapsible: false,
      items: [
        {
          type: "category",
          label: "概要",
          items: ["swiftui/essentials/about/index"],
        },
      ],
    },
  ],
};

module.exports = sidebars;
